# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'AlamofireStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'

  # Pods for AlamofireStudy

end
